Repository crewAIInc/crewAI, pull requests merged in 2024-08, with the labels that each got.

#961 Handling minor buggy issue: tools name shouldn't contain space for OpenAI
  src/crewai/tools/tool_usage.py
Labels: bug

#628 Added Firecrawl tools to docs
  docs/tools/FirecrawlCrawlWebsiteTool.md
  docs/tools/FirecrawlScrapeWebsiteTool.md
  docs/tools/FirecrawlSearchTool.md
  mkdocs.yml
Labels: documentation

#1182 updated bug report template to yml for more control
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: improvement

#1194 Updated Documentation to fix minor issues + minor .github fixes
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/custom.md
  mkdocs.yml
Labels: documentation

#1165 docs: add spider docs
  docs/tools/SpiderTool.md
  mkdocs.yml
Labels: documentation
